import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {supabase} from './lib/supabase'
import './styles.css'

const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0))
const statusLabel={available:'Disponível',reserved:'Reservado',sold:'Vendido'}

function Login({onLogin}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function submit(e){e.preventDefault();setBusy(true);setError('');if(!supabase){setError('Configure o VITE_SUPABASE_PUBLISHABLE_KEY no arquivo .env');setBusy(false);return}
 const {data,error}=await supabase.auth.signInWithPassword({email,password}); if(error)setError(error.message);else onLogin(data.user);setBusy(false)}
 return <div className="login"><div className="login-card"><div className="brand">LAOCAR</div><p>Gestão de Vendas</p><form onSubmit={submit}><input placeholder="E-mail" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><input placeholder="Senha" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button disabled={busy}>{busy?'Entrando…':'Entrar'}</button>{error&&<div className="error">{error}</div>}</form></div></div>
}

function App(){
 const [user,setUser]=useState(null),[page,setPage]=useState('dashboard'),[storeId,setStoreId]=useState(null),[dash,setDash]=useState(null),[vehicles,setVehicles]=useState([]),[customers,setCustomers]=useState([]),[sales,setSales]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[filter,setFilter]=useState('all')
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setUser(data.session?.user||null));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>subscription.unsubscribe()},[])
 useEffect(()=>{if(!user)return;loadStore()},[user])
 async function loadStore(){setLoading(true);const {data}=await supabase.from('store_members').select('store_id').eq('user_id',user.id).limit(1).maybeSingle();if(data?.store_id){setStoreId(data.store_id);await Promise.all([loadDash(data.store_id),loadInventory(data.store_id),loadCustomers(data.store_id),loadSales(data.store_id)])}setLoading(false)}
 async function loadDash(id){const {data}=await supabase.rpc('dashboard_summary',{p_store_id:id});setDash(data?.[0]||data||{})}
 async function loadInventory(id){const {data,error}=await supabase.rpc('inventory_summary',{p_store_id:id});if(!error)setVehicles(Array.isArray(data)?data:(data?.vehicles||[]))}
  async function loadCustomers(id){const {data,error}=await supabase.rpc('customer_summary',{p_store_id:id});if(!error)setCustomers(Array.isArray(data)?data:(data?.customers||[]))}
  async function loadSales(id){const {data,error}=await supabase.rpc('recent_sales',{p_store_id:id,p_limit:50});if(!error)setSales(Array.isArray(data)?data:(data?.sales||[]))}
 async function logout(){await supabase.auth.signOut()}
 if(!user)return <Login onLogin={setUser}/>
 const filtered=vehicles.filter(v=>(filter==='all'||v.status===filter)&&(`${v.make||''} ${v.model||''} ${v.plate||''}`.toLowerCase().includes(search.toLowerCase())))
 return <div className="app"><aside><div className="brand">LAOCAR</div><small>Gestão de Vendas</small>{['dashboard','estoque','clientes','anuncios','vendas','documentos','relatorios','config'].map(p=><button className={page===p?'nav active':'nav'} onClick={()=>setPage(p)} key={p}>{({dashboard:'Dashboard',estoque:'Estoque',clientes:'Clientes',anuncios:'Anúncios',vendas:'Vendas',documentos:'Documentos',relatorios:'Relatórios',config:'Configurações'})[p]}</button>)}<button className="nav logout" onClick={logout}>Sair</button></aside><main><header><div><h1>{page==='dashboard'?'Dashboard':'Estoque'}</h1><span>{user.email}</span></div></header>{page==='dashboard'?<Dashboard dash={dash} loading={loading}/>:page==='estoque'?<Inventory vehicles={filtered} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} refresh={()=>storeId&&loadInventory(storeId)}/>:<Placeholder title={({clientes:'Clientes',anuncios:'Anúncios',vendas:'Vendas',documentos:'Documentos',relatorios:'Relatórios',config:'Configurações'})[page]}/>}</main></div>
}
function Dashboard({dash,loading}){const d=dash||{};return <section><div className="cards"><Card title="Veículos" value={d.vehicles_total??d.total_vehicles??0}/><Card title="Disponíveis" value={d.vehicles_available??d.available_vehicles??0}/><Card title="Vendas concluídas" value={d.sales_completed??d.completed_sales??0}/><Card title="Faturamento" value={money(d.revenue??d.total_revenue)}/></div><div className="panel"><h2>Resumo da operação</h2><p>{loading?'Carregando dados do Supabase…':'Dados conectados ao banco da Laocar.'}</p></div></section>}
function Card({title,value}){return <div className="card"><span>{title}</span><strong>{value}</strong></div>}
function Inventory({vehicles,search,setSearch,filter,setFilter,refresh}){
 const [show,setShow]=useState(false),[pv,setPv]=useState(null),[photos,setPhotos]=useState([]),[files,setFiles]=useState([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function signed(path){if(!path)return '';if(path.startsWith('http'))return path;const {data}=await supabase.storage.from('vehicle-photos').createSignedUrl(path,3600);return data?.signedUrl||''}
 async function loadPhotos(id){const {data,error}=await supabase.from('vehicle_photos').select('*').eq('vehicle_id',id).order('sort_order').order('created_at');if(error){setMsg(error.message);return}setPhotos(await Promise.all((data||[]).map(async p=>({...p,url:await signed(p.storage_path)}))))}
 async function open(v){setPv(v);setMsg('');setFiles([]);await loadPhotos(v.id)}
 function choose(e){const a=Array.from(e.target.files||[]);if(a.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>10485760)){setMsg('Use JPG, PNG ou WebP com até 10 MB por foto.');setFiles([]);return}setFiles(a)}
 async function upload(){if(!files.length)return;setBusy(true);try{const {data:ss}=await supabase.auth.getSession(),user=ss?.session?.user;if(!user)throw Error('Sessão não encontrada');const {data:m,error:me}=await supabase.from('store_members').select('store_id').eq('user_id',user.id).limit(1).single();if(me)throw me;const sid=m.store_id;const {data:vc,error:ve}=await supabase.from('vehicles').select('id').eq('id',pv.id).eq('store_id',sid).single();if(ve||!vc)throw Error('Veículo não pertence à loja.');const {data:last}=await supabase.from('vehicle_photos').select('sort_order').eq('vehicle_id',pv.id).order('sort_order',{ascending:false}).limit(1);const {data:cov}=await supabase.from('vehicle_photos').select('id').eq('vehicle_id',pv.id).eq('is_cover',true).limit(1);let n=(last?.[0]?.sort_order??-1)+1,has=!!cov?.length;for(const f of files){const ext=(f.name.split('.').pop()||'jpg').toLowerCase(),path=`${sid}/${pv.id}/${crypto.randomUUID()}.${ext}`;const {error:u}=await supabase.storage.from('vehicle-photos').upload(path,f,{contentType:f.type,upsert:false});if(u)throw u;const {error:r}=await supabase.from('vehicle_photos').insert({vehicle_id:pv.id,storage_path:path,sort_order:n++,is_cover:!has});if(r){await supabase.storage.from('vehicle-photos').remove([path]);throw r}has=true}setFiles([]);setMsg('Fotos adicionadas.');await loadPhotos(pv.id);await refresh()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function cover(p){setBusy(true);try{let {error}=await supabase.from('vehicle_photos').update({is_cover:false}).eq('vehicle_id',pv.id);if(error)throw error;({error}=await supabase.from('vehicle_photos').update({is_cover:true}).eq('id',p.id));if(error)throw error;await loadPhotos(pv.id);await refresh()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function del(p){setBusy(true);try{const was=p.is_cover;const {error}=await supabase.from('vehicle_photos').delete().eq('id',p.id);if(error)throw error;await supabase.storage.from('vehicle-photos').remove([p.storage_path]);if(was){const {data:r}=await supabase.from('vehicle_photos').select('id').eq('vehicle_id',pv.id).order('sort_order').limit(1);if(r?.[0])await supabase.from('vehicle_photos').update({is_cover:true}).eq('id',r[0].id)}await loadPhotos(pv.id);await refresh()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function move(i,d){const j=i+d;if(j<0||j>=photos.length)return;const a=photos[i],b=photos[j];setBusy(true);try{let {error}=await supabase.from('vehicle_photos').update({sort_order:b.sort_order}).eq('id',a.id);if(error)throw error;({error}=await supabase.from('vehicle_photos').update({sort_order:a.sort_order}).eq('id',b.id));if(error)throw error;await loadPhotos(pv.id)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 const shown=vehicles.filter(v=>(filter==='all'||v.status===filter)&&(`${v.make||''} ${v.model||''} ${v.plate||''}`.toLowerCase().includes(search.toLowerCase())));
 return <section><div className="toolbar"><input placeholder="Buscar marca, modelo ou placa…" value={search} onChange={e=>setSearch(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option><option value="available">Disponíveis</option><option value="reserved">Reservados</option><option value="sold">Vendidos</option></select><button className="primary" onClick={()=>setShow(true)}>+ Novo veículo</button></div>
 <div className="inventory-grid">{shown.map(v=><div className="vehicle-card" key={v.id}><VehicleCover path={v.cover_photo}/><div className="vehicle-info"><strong>{v.make} {v.model} {v.version||''}</strong><span>{v.model_year||''} • {v.mileage??0} km</span><span>{v.plate||'Sem placa'}</span><b>{v.sale_price!=null?Number(v.sale_price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'Preço não informado'}</b><button onClick={()=>open(v)}>📸 Fotos do veículo</button></div></div>)}</div>
 {show&&<VehicleForm onClose={()=>setShow(false)} onSaved={async()=>{setShow(false);await refresh()}}/>}
 {pv&&<div className="modal-back"><div className="modal photo-modal"><div className="modal-head"><h2>Fotos — {pv.make} {pv.model}</h2><button onClick={()=>setPv(null)}>×</button></div><div className="upload-zone"><input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={choose}/><button disabled={!files.length||busy} onClick={upload}>Enviar {files.length||''} foto(s)</button></div>{msg&&<p className="notice">{msg}</p>}<div className="photo-grid">{photos.map((p,i)=><div className="photo-item" key={p.id}><img src={p.url}/>{p.is_cover&&<span className="cover-badge">CAPA</span>}<div className="photo-actions"><button disabled={p.is_cover||busy} onClick={()=>cover(p)}>Capa</button><button disabled={i===0||busy} onClick={()=>move(i,-1)}>←</button><button disabled={i===photos.length-1||busy} onClick={()=>move(i,1)}>→</button><button disabled={busy} onClick={()=>del(p)}>Excluir</button></div></div>)}</div></div></div>}</section>
}
function VehicleCover({path}){const [u,setU]=useState('');useEffect(()=>{let alive=true;(async()=>{if(!path)return; if(path.startsWith('http')){if(alive)setU(path);return}const {data}=await supabase.storage.from('vehicle-photos').createSignedUrl(path,3600);if(alive)setU(data?.signedUrl||'')})();return()=>{alive=false}},[path]);return u?<img className="vehicle-cover" src={u}/>:<div className="vehicle-cover photo-placeholder">Sem foto</div>}

function VehicleForm({onClose,onSaved}){
 const [form,setForm]=useState({plate:'',mileage:'',sale_price:'',notes:''}),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 function set(k,v){setForm(x=>({...x,[k]:v}))}
 async function save(e){e.preventDefault();setBusy(true);setMsg('')
 const {data:{session}}=await supabase.auth.getSession()
 if(!session){setMsg('Sessão expirada.');setBusy(false);return}
 const {data:member}=await supabase.from('store_members').select('store_id').eq('user_id',session.user.id).limit(1).maybeSingle()
 if(!member?.store_id){setMsg('Usuário sem loja vinculada.');setBusy(false);return}
 const {data,error}=await supabase.functions.invoke('vehicle-create',{body:{store_id:member.store_id,plate:form.plate,mileage:Number(form.mileage)||0,sale_price:Number(form.sale_price)||null,notes:form.notes}})
 if(error){setMsg(error.message||'Não foi possível cadastrar.')}else{onSaved(data)}
 setBusy(false)}
 return <div className="modal-back"><div className="modal"><div className="modal-head"><h2>Novo veículo</h2><button onClick={onClose}>×</button></div><p className="muted">Informe a placa para buscar os dados do veículo e FIPE.</p><form onSubmit={save} className="vehicle-form"><input placeholder="Placa" value={form.plate} onChange={e=>set('plate',e.target.value.toUpperCase())} required/><input type="number" placeholder="Quilometragem" value={form.mileage} onChange={e=>set('mileage',e.target.value)}/><input type="number" step="0.01" placeholder="Preço de venda" value={form.sale_price} onChange={e=>set('sale_price',e.target.value)}/><textarea placeholder="Observações" value={form.notes} onChange={e=>set('notes',e.target.value)}/><div className="modal-actions"><button type="button" onClick={onClose}>Cancelar</button><button disabled={busy} type="submit">{busy?'Consultando FIPE…':'Cadastrar veículo'}</button></div>{msg&&<div className="error">{msg}</div>}</form></div></div>
}

function Customers({storeId,customers,refresh}){
 const [show,setShow]=useState(false),[selected,setSelected]=useState(null),[history,setHistory]=useState([]),[msg,setMsg]=useState(''),[q,setQ]=useState('');
 const list=(customers||[]).filter(c=>`${c.name||c.full_name||''} ${c.cpf||''} ${c.phone||c.mobile_phone||''} ${c.email||''}`.toLowerCase().includes(q.toLowerCase()));
 async function open(c){setSelected(c);setMsg('');const {data,error}=await supabase.rpc('customer_sales_history',{p_store_id:storeId,p_customer_id:c.id});if(error)setMsg(error.message);else setHistory(Array.isArray(data)?data:(data?.sales||[]))}
 return <section>
  <div className="toolbar"><input placeholder="Buscar cliente, CPF, telefone ou e-mail…" value={q} onChange={e=>setQ(e.target.value)}/><button className="primary" onClick={()=>setShow(true)}>+ Novo cliente</button></div>
  <div className="customer-grid">{list.map(c=><div className="customer-card" key={c.id} onClick={()=>open(c)}><strong>{c.name||c.full_name}</strong><span>CPF: {c.cpf||'Não informado'}</span><span>{c.phone||c.mobile_phone||'Sem telefone'}</span><span>{c.email||'Sem e-mail'}</span><small>{c.sales_count||0} venda(s)</small></div>)}</div>
  {!list.length&&<div className="card">Nenhum cliente encontrado.</div>}
  {show&&<CustomerForm storeId={storeId} onClose={()=>setShow(false)} onSaved={async()=>{setShow(false);await refresh()}}/>}
  {selected&&<div className="modal-back"><div className="modal customer-modal"><div className="modal-head"><h2>{selected.name||selected.full_name}</h2><button onClick={()=>setSelected(null)}>×</button></div>{msg&&<p className="notice">{msg}</p>}
   <div className="customer-detail"><p><b>CPF:</b> {selected.cpf||'—'}</p><p><b>Telefone:</b> {selected.phone||selected.mobile_phone||'—'}</p><p><b>E-mail:</b> {selected.email||'—'}</p></div>
   <h3>Histórico de vendas</h3>{history.length?<div className="history-list">{history.map(h=><div className="history-row" key={h.id}><span>{h.sale_date||''}</span><strong>{h.make||''} {h.model||''}</strong><span>{h.plate||''}</span><b>{h.sale_price!=null?Number(h.sale_price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):''}</b></div>)}</div>:<p className="muted">Nenhuma venda registrada.</p>}
  </div></div>}
 </section>
}
function CustomerForm({storeId,onClose,onSaved}){
 const [busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[f,setF]=useState({full_name:'',cpf:'',rg:'',birth_date:'',mother_name:'',mobile_phone:'',email:'',street:'',number:'',zip_code:'',city:'',state:''});
 function set(k,v){setF({...f,[k]:v})}
 async function save(e){e.preventDefault();setBusy(true);setMsg('');try{const {data:ss}=await supabase.auth.getSession(),uid=ss?.session?.user?.id;if(!uid)throw Error('Sessão não encontrada');const payload={store_id:storeId,created_by:uid,full_name:f.full_name,cpf:f.cpf||null,mobile_phone:f.mobile_phone||null,email:f.email||null};
   const {error}=await supabase.from('customers').insert(payload);if(error)throw error;await onSaved()
  }catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <div className="modal-back"><form className="modal customer-form" onSubmit={save}><div className="modal-head"><h2>Novo cliente</h2><button type="button" onClick={onClose}>×</button></div>{msg&&<p className="notice">{msg}</p>}
  <div className="form-grid"><label className="wide">Nome completo<input required value={f.full_name} onChange={e=>set('full_name',e.target.value)}/></label><label>CPF<input value={f.cpf} onChange={e=>set('cpf',e.target.value)}/></label><label>RG<input value={f.rg} onChange={e=>set('rg',e.target.value)}/></label><label>Data de nascimento<input type="date" value={f.birth_date} onChange={e=>set('birth_date',e.target.value)}/></label><label>Nome da mãe<input value={f.mother_name} onChange={e=>set('mother_name',e.target.value)}/></label><label>Celular<input value={f.mobile_phone} onChange={e=>set('mobile_phone',e.target.value)}/></label><label>E-mail<input type="email" value={f.email} onChange={e=>set('email',e.target.value)}/></label><label>CEP<input value={f.zip_code} onChange={e=>set('zip_code',e.target.value)}/></label><label className="wide">Endereço<input value={f.street} onChange={e=>set('street',e.target.value)}/></label><label>Número<input value={f.number} onChange={e=>set('number',e.target.value)}/></label><label>Cidade<input value={f.city} onChange={e=>set('city',e.target.value)}/></label><label>UF<input maxLength="2" value={f.state} onChange={e=>set('state',e.target.value.toUpperCase())}/></label></div>
  <p className="muted">Os campos adicionais de endereço e identificação ficam preparados na interface; nesta versão são gravados apenas os campos existentes atualmente na tabela de clientes.</p>
  <div className="modal-actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar cliente'}</button></div>
 </form></div>
}

function Sales({storeId,sales,vehicles,customers,refresh}){
 const [show,setShow]=useState(false),[msg,setMsg]=useState('');
 return <section><div className="toolbar"><div><h2>Vendas</h2><span className="muted">Negociações, reservas e vendas concluídas</span></div><button className="primary" onClick={()=>setShow(true)}>+ Nova venda</button></div>
 {msg&&<p className="notice">{msg}</p>}
 <div className="sales-table"><div className="sales-head"><span>Nº</span><span>Data</span><span>Veículo</span><span>Cliente</span><span>Valor</span><span>Status</span><span>Documentos</span></div>
 {(sales||[]).map(x=><div className="sales-row" key={x.id}><span>{x.sale_number||'—'}</span><span>{x.sale_date||'—'}</span><span>{x.make||''} {x.model||''}<small>{x.plate||''}</small></span><span>{x.customer_name||'—'}</span><b>{x.sale_price!=null?Number(x.sale_price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—'}</b><span className={'pill '+(x.status||'')}>{x.status||'—'}</span><span>{x.documents_status||'pending'}</span></div>)}</div>
 {!sales?.length&&<div className="card">Nenhuma venda cadastrada.</div>}
 {show&&<SaleForm storeId={storeId} vehicles={vehicles} customers={customers} onClose={()=>setShow(false)} onSaved={async sale=>{setShow(false);setMsg('Venda criada e veículo reservado.');await refresh()}}/>}
 </section>
}
function SaleForm({storeId,vehicles,customers,onClose,onSaved}){
 const available=(vehicles||[]).filter(v=>v.status==='available');
 const [busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[f,setF]=useState({vehicle_id:'',customer_id:'',sale_price:'',purchase_cost:'',payment_method:'',down_payment:'',financed_amount:'',installments:'',first_due_date:'',notes:''});
 function set(k,v){setF({...f,[k]:v})}
 function pickVehicle(id){const v=available.find(x=>x.id===id);setF({...f,vehicle_id:id,sale_price:v?.sale_price??f.sale_price})}
 async function save(e){e.preventDefault();setBusy(true);setMsg('');try{
   const body={store_id:storeId,vehicle_id:f.vehicle_id,customer_id:f.customer_id,sale_price:Number(f.sale_price),purchase_cost:f.purchase_cost?Number(f.purchase_cost):null,payment_method:f.payment_method||null,down_payment:f.down_payment?Number(f.down_payment):null,financed_amount:f.financed_amount?Number(f.financed_amount):null,installments:f.installments?Number(f.installments):null,first_due_date:f.first_due_date||null,notes:f.notes||null};
   const {data,error}=await supabase.functions.invoke('sale-create',{body});if(error)throw error;if(data?.error)throw Error(data.error);await onSaved(data?.sale||data)
 }catch(e){setMsg(e.message||'Erro ao criar venda.')}finally{setBusy(false)}}
 return <div className="modal-back"><form className="modal sale-form" onSubmit={save}><div className="modal-head"><h2>Nova venda</h2><button type="button" onClick={onClose}>×</button></div>{msg&&<p className="notice">{msg}</p>}
 <div className="form-grid"><label className="wide">Veículo<select required value={f.vehicle_id} onChange={e=>pickVehicle(e.target.value)}><option value="">Selecione</option>{available.map(v=><option key={v.id} value={v.id}>{v.make} {v.model} {v.version||''} — {v.plate||'sem placa'}</option>)}</select></label>
 <label className="wide">Cliente<select required value={f.customer_id} onChange={e=>set('customer_id',e.target.value)}><option value="">Selecione</option>{(customers||[]).map(c=><option key={c.id} value={c.id}>{c.name||c.full_name} — {c.cpf||'sem CPF'}</option>)}</select></label>
 <label>Valor da venda<input required type="number" min="0.01" step="0.01" value={f.sale_price} onChange={e=>set('sale_price',e.target.value)}/></label><label>Custo de compra<input type="number" min="0" step="0.01" value={f.purchase_cost} onChange={e=>set('purchase_cost',e.target.value)}/></label>
 <label>Forma de pagamento<select value={f.payment_method} onChange={e=>set('payment_method',e.target.value)}><option value="">Selecione</option><option>À vista</option><option>Financiamento</option><option>Entrada + financiamento</option><option>Troca + diferença</option></select></label><label>Entrada<input type="number" min="0" step="0.01" value={f.down_payment} onChange={e=>set('down_payment',e.target.value)}/></label>
 <label>Valor financiado<input type="number" min="0" step="0.01" value={f.financed_amount} onChange={e=>set('financed_amount',e.target.value)}/></label><label>Parcelas<input type="number" min="1" value={f.installments} onChange={e=>set('installments',e.target.value)}/></label>
 <label>Primeiro vencimento<input type="date" value={f.first_due_date} onChange={e=>set('first_due_date',e.target.value)}/></label><label className="wide">Observações<textarea rows="3" value={f.notes} onChange={e=>set('notes',e.target.value)}/></label></div>
 <div className="modal-actions"><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={busy||!available.length}>{busy?'Criando venda…':'Criar venda e reservar veículo'}</button></div>
 {!available.length&&<p className="muted">Não há veículos disponíveis para uma nova venda.</p>}</form></div>
}

function Documents({storeId,sales}){
 const [saleId,setSaleId]=useState(''),[docs,setDocs]=useState([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[status,setStatus]=useState(null);
 async function load(id=saleId){if(!id)return;setBusy(true);setMsg('');try{const {data,error}=await supabase.from('sale_documents').select('id,sale_id,document_type,document_number,pdf_path,created_at').eq('sale_id',id).order('created_at');if(error)throw error;setDocs(data||[]);const {data:st,error:se}=await supabase.rpc('sale_signature_status',{p_sale_id:id});if(!se)setStatus(st)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function selectSale(id){setSaleId(id);setDocs([]);setStatus(null);if(id){setTimeout(()=>{},0);setBusy(true);try{const {data,error}=await supabase.from('sale_documents').select('id,sale_id,document_type,document_number,pdf_path,created_at').eq('sale_id',id).order('created_at');if(error)throw error;setDocs(data||[]);const {data:st}=await supabase.rpc('sale_signature_status',{p_sale_id:id});setStatus(st)}catch(e){setMsg(e.message)}finally{setBusy(false)}}}
 async function bundle(){if(!saleId)return;setBusy(true);setMsg('');try{const {data,error}=await supabase.functions.invoke('sale-documents-bundle',{body:{sale_id:saleId}});if(error)throw error;if(data?.error)throw Error(data.error);setMsg('Contrato e pedido de venda preparados.');await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function pdf(doc){setBusy(true);try{const {data,error}=await supabase.functions.invoke('sale-document-pdf',{body:{sale_document_id:doc.id}});if(error)throw error;if(data?.error)throw Error(data.error);if(data?.signed_url)window.open(data.signed_url,'_blank');await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function download(doc){setBusy(true);try{const {data,error}=await supabase.functions.invoke('sale-document-download',{body:{sale_document_id:doc.id}});if(error)throw error;if(data?.error)throw Error(data.error);if(data?.signed_url)window.open(data.signed_url,'_blank')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function sellerSign(doc){const name=window.prompt('Nome completo do vendedor para assinatura:');if(!name)return;setBusy(true);try{const {data,error}=await supabase.functions.invoke('sale-document-sign',{body:{sale_id:saleId,document_type:doc.document_type,role:'seller',signature_name:name}});if(error)throw error;if(data?.error)throw Error(data.error);setMsg('Assinatura do vendedor registrada.');await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function signatureLink(doc,role){setBusy(true);try{const {data,error}=await supabase.functions.invoke('sale-signature-request',{body:{sale_id:saleId,document_type:doc.document_type,role}});if(error)throw error;if(data?.error)throw Error(data.error);const token=data?.token;if(!token)throw Error('Token de assinatura não retornado.');const link=`${window.location.origin}${window.location.pathname}?signature_token=${encodeURIComponent(token)}`;await navigator.clipboard?.writeText(link);setMsg(`Link de assinatura (${role}) criado e copiado: ${link}`)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function finalize(){setBusy(true);try{const {data,error}=await supabase.functions.invoke('sale-documents-finalize',{body:{sale_id:saleId}});if(error)throw error;if(data?.error)throw Error(data.error);setMsg(`Documentos: ${data?.status||'atualizados'}.`);await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 const st=status?.contract?status:null;
 return <section><div className="toolbar"><div><h2>Documentos e assinaturas</h2><span className="muted">Contrato, pedido de venda e acompanhamento das assinaturas</span></div></div>
 <div className="doc-controls"><select value={saleId} onChange={e=>selectSale(e.target.value)}><option value="">Selecione uma venda</option>{(sales||[]).map(x=><option key={x.id} value={x.id}>{x.sale_number||x.id.slice(0,8)} — {x.customer_name||''} — {x.make||''} {x.model||''}</option>)}</select><button className="primary" disabled={!saleId||busy} onClick={bundle}>Gerar documentos</button><button disabled={!saleId||busy} onClick={finalize}>Atualizar status</button></div>
 {msg&&<p className="notice doc-message">{msg}</p>}
 {busy&&<p className="muted">Processando…</p>}
 <div className="doc-grid">{docs.map(d=><div className="doc-card" key={d.id}><div><strong>{d.document_type==='contract'?'Contrato de compra e venda':'Pedido de venda'}</strong><span>{d.document_number||'Sem número'}</span></div><div className="doc-actions"><button onClick={()=>pdf(d)} disabled={busy}>{d.pdf_path?'Gerar novo PDF':'Gerar PDF'}</button>{d.pdf_path&&<button onClick={()=>download(d)} disabled={busy}>Abrir PDF</button>}<button onClick={()=>sellerSign(d)} disabled={busy}>Assinar vendedor</button><button onClick={()=>signatureLink(d,'buyer')} disabled={busy}>Link comprador</button><button onClick={()=>signatureLink(d,'witness1')} disabled={busy}>Link testemunha 1</button><button onClick={()=>signatureLink(d,'witness2')} disabled={busy}>Link testemunha 2</button></div></div>)}</div>
 {!docs.length&&saleId&&!busy&&<div className="card">Nenhum documento gerado para esta venda.</div>}
 {status&&<div className="signature-panel"><h3>Status das assinaturas</h3><SignatureStatus title="Contrato" data={status.contract}/><SignatureStatus title="Pedido de venda" data={status.sales_order}/></div>}
 </section>
}
function SignatureStatus({title,data}){
 const x=data||{};return <div className="signature-row"><strong>{title}</strong><span>{x.seller_signed?'✓':'○'} Vendedor</span><span>{x.buyer_signed?'✓':'○'} Comprador</span><span>{x.witness1_signed?'✓':'○'} Testemunha 1</span><span>{x.witness2_signed?'✓':'○'} Testemunha 2</span></div>
}

function Ads({storeId,vehicles}){
 const [items,setItems]=useState([]),[vehicleId,setVehicleId]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function load(){const {data,error}=await supabase.rpc('ad_inventory_summary',{p_store_id:storeId});if(error)setMsg(error.message);else setItems(Array.isArray(data)?data:(data?.ads||[]))}
 useEffect(()=>{if(storeId)load()},[storeId]);
 async function generate(){if(!vehicleId)return;setBusy(true);setMsg('');try{const {data,error}=await supabase.functions.invoke('ad-generate',{body:{vehicle_id:vehicleId}});if(error)throw error;if(data?.error)throw Error(data.error);setMsg('Anúncio gerado com título, descrição e conteúdo social.');await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <section><div className="toolbar"><div><h2>Anúncios</h2><span className="muted">Conteúdo automático para divulgação dos veículos</span></div></div><div className="module-controls"><select value={vehicleId} onChange={e=>setVehicleId(e.target.value)}><option value="">Selecione um veículo</option>{(vehicles||[]).map(v=><option key={v.id} value={v.id}>{v.make} {v.model} — {v.plate||'sem placa'}</option>)}</select><button className="primary" disabled={!vehicleId||busy} onClick={generate}>{busy?'Gerando…':'Gerar anúncio'}</button></div>{msg&&<p className="notice">{msg}</p>}<div className="ad-grid">{items.map(a=><div className="ad-card" key={a.id}><strong>{a.title||`${a.make||''} ${a.model||''}`}</strong><span>{a.status||'draft'}</span><p>{a.description||'Conteúdo preparado para divulgação.'}</p><small>{a.plate||''} {a.model_year||''}</small></div>)}</div></section>
}
function Reports({storeId}){
 const [sales,setSales]=useState(null),[stock,setStock]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function load(){setBusy(true);setMsg('');try{const [a,b]=await Promise.all([supabase.rpc('sales_report',{p_store_id:storeId,p_start_date:null,p_end_date:null}),supabase.rpc('inventory_report',{p_store_id:storeId})]);if(a.error)throw a.error;if(b.error)throw b.error;setSales(a.data);setStock(b.data)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(storeId)load()},[storeId]);
 const ss=sales?.summary||sales?.[0]?.summary||sales||{},st=stock?.summary||stock?.[0]?.summary||stock||{};
 const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 return <section><div className="toolbar"><div><h2>Relatórios</h2><span className="muted">Vendas, faturamento e posição do estoque</span></div><button onClick={load} disabled={busy}>Atualizar</button></div>{msg&&<p className="notice">{msg}</p>}<div className="report-grid"><Card title="Vendas concluídas" value={ss.sales_count??0}/><Card title="Faturamento" value={money(ss.revenue)}/><Card title="Ticket médio" value={money(ss.average_sale)}/><Card title="Estoque total" value={st.total??0}/><Card title="Disponíveis" value={st.available??0}/><Card title="Reservados" value={st.reserved??0}/><Card title="Vendidos" value={st.sold??0}/><Card title="Valor do estoque" value={money(st.stock_sale_value)}/></div><p className="muted">O custo/margem potencial do estoque depende de um custo de aquisição persistido por veículo; o relatório não inventa esse valor.</p></section>
}
function Settings({storeId}){
 const [settings,setSettings]=useState(null),[access,setAccess]=useState(null),[sub,setSub]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function load(){setBusy(true);try{const [a,b,c]=await Promise.all([supabase.rpc('store_settings_summary',{p_store_id:storeId}),supabase.rpc('my_store_access',{p_store_id:storeId}),supabase.rpc('subscription_status',{p_store_id:storeId})]);if(a.error)throw a.error;if(b.error)throw b.error;if(c.error)throw c.error;setSettings(a.data);setAccess(b.data);setSub(c.data)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(storeId)load()},[storeId]);
 const st=settings?.store||settings?.[0]?.store||settings||{},ac=access?.[0]||access||{},su=sub?.[0]||sub||{};
 return <section><div className="toolbar"><div><h2>Configurações</h2><span className="muted">Loja, equipe, permissões e assinatura</span></div><button onClick={load} disabled={busy}>Atualizar</button></div>{msg&&<p className="notice">{msg}</p>}<div className="settings-grid"><div className="settings-card"><h3>Loja</h3><p><b>{st.name||st.store_name||'Laocar'}</b></p><p>{st.phone||''}</p><p>{st.email||''}</p></div><div className="settings-card"><h3>Meu acesso</h3><p>Perfil: <b>{ac.role||ac.my_role||'—'}</b></p><p>{ac.can_manage_inventory?'✓':'○'} Estoque</p><p>{ac.can_create_sales?'✓':'○'} Vendas</p><p>{ac.can_view_reports?'✓':'○'} Relatórios</p></div><div className="settings-card"><h3>Plano</h3><p><b>{su.plan_name||'Laocar 5'}</b></p><p>Status: {su.status||'none'}</p><p>{su.monthly_price!=null?Number(su.monthly_price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):''}</p></div></div></section>
}

function Placeholder({title}){return <section><div className="panel"><h2>{title}</h2><p>Módulo preparado para a próxima etapa da interface do Laocar.</p></div></section>}
createRoot(document.getElementById('root')).render(<App/>)

if ('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
